return {
    Cursor = { fg = 'MAGENTA', bg = 'WHITE' },
    Visual = { reverse = true },
    CursorLine = { bg = 'BLACK' },
    CursorColumn = { bg = 'BLACK' },
    ColorColumn = { bg = 'darker_gray' },
    LineNr = { fg = 'dark_gray', bg = 'BLACK' },
    VertSplit = { fg = 'dark_gray', bg = 'BLACK', bold = true },
    MatchParen = { fg = 'RED', reverse = true },
    StatusLine = { fg = 'WHITE', bg = 'darker_gray', bold = true },
    StatusLineNC = { fg = 'WHITE', bg = 'darker_gray' },
    Pmenu = { fg = 'WHITE', bg = 'darker_gray' },
    PmenuSel = { bg = 'BLACK' },
    IncSearch = { fg = 'BLACK', bg = 'YELLOW' },
    Search = { fg = 'YELLOW', bg = 'MAGENTA', underline = true },
    Directory = { fg = 'MAGENTA' },
    Folded = { fg = 'MAGENTA', bg = 'BLACK' },
    SignColumn = { fg = 'darker_gray', bg = 'BLACK' },
    FoldColmun = { fg = 'darker_gray', bg = 'BLACK' },
    Normal = { fg = 'WHITE', bg = 'BLACK' },
    Boolean = { fg = 'MAGENTA' },
    Character = { fg = 'GREEN' },
    Comment = { fg = 'GREEN' },
    Conditional = { fg = 'RED' },
    Constant = { fg = 'WHITE', bold = true },
    Define = { fg = 'RED' },

    healthError = { fg = 'RED' },
    healthSuccess = { fg = 'GREEN' },
    healthWarning = { fg = 'YELLOW' },

    GlyphPalette1 = { fg = 'RED' },
    GlyphPalette2 = { fg = 'YELLOW' },
    GlyphPalette3 = { fg = 'GREEN' },
    GlyphPalette4 = { fg = 'BLUE' },
    GlyphPalette6 = { fg = 'MAGENTA' },
    GlyphPalette7 = { fg = 'light_gray' },
    GlyphPalette9 = { fg = 'dark_gray' },

    rainbow1 = { fg = 'RED' },
    rainbow2 = { fg = 'YELLOW' },
    rainbow3 = { fg = 'GREEN' },
    rainbow4 = { fg = 'BLUE' },
    rainbow5 = { fg = 'MAGENTA' },
    rainbow6 = { fg = 'darker_gray' },

    RainbowDelimiterYellow = { fg = 'YELLOW' },
    RainbowDelimiterBlue = { fg = 'BLUE' },
    RainbowDelimiterOrange = { fg = 'RED' },
    RainbowDelimiterGreen = { fg = 'GREEN' },
    RainbowDelimiterViolet = { fg = 'MAGENTA' },
    RainbowDelimiterCyan = { fg = 'BLUE' },
    RainbowDelimiterRed = { fg = 'RED' },

    TroubleIndentWs = { fg = 'WHITE' },
    TroubleIndentTop = { fg = 'WHITE' },
    TroubleIndentMiddle = { fg = 'WHITE' },
    TroubleIndentLast = { fg = 'WHITE' },
    TroubleIndentFoldOpen = { fg = 'WHITE' },
    TroubleDiagnosticsPos = { fg = 'WHITE' },

    DiffAdd = { fg = 'WHITE', bg = 'GREEN', bold = true },
    DiffDelete = { fg = 'RED', bold = true },

    DiffLine = { fg = 'MAGENTA', italic = true },
    DiffText = { fg = 'WHITE', bg = 'BLUE', bold = true },
    diffSubName = { fg = 'MAGENTA', bg = 'BLACK', bold = true },

    GitSignsAdd = { bg = 'GREEN' },
    GitSignsRemoved = { bg = 'RED' },
    GitSignsChange = { bg = 'BLUE' },
    DiffChange = { bg = 'BLUE' },

    DiffAdded = { fg = 'GREEN' },
    DiffRemoved = { fg = 'RED' },

    fugitiveHunk = { fg = 'light_gray', italic = true },

    fugitiveUntrackedHeading = { fg = 'RED', bold = true, italic = false },
    fugitiveUnstagedHeading = { fg = 'BLUE', bold = true, italic = false },
    fugitiveStagedHeading = { fg = 'MAGENTA', bold = true, italic = false },

    fugitiveUntrackedSection = { fg = 'WHITE', italic = true },
    fugitiveUnstagedSection = { fg = 'WHITE', italic = true },
    fugitiveStagedSection = { fg = 'WHITE', italic = true },

    fugitiveUntrackedModifier = { fg = 'RED', bold = true, italic = false },
    fugitiveUnstagedModifier = { fg = 'BLUE', bold = true, italic = false },
    fugitiveStagedModifier = { fg = 'MAGENTA', bold = true, italic = false },

    ErrorMsg = { fg = 'WHITE', bg = 'RED' },
    WarningMsg = { fg = 'WHITE', bg = 'RED' },
    Float = { fg = 'MAGENTA' },
    Function = { fg = 'YELLOW' },
    Identifier = { fg = 'WHITE' },
    Keyword = { fg = 'MAGENTA', bold = true },
    Label = { fg = 'YELLOW' },
    NonText = { fg = 'darker_gray', bg = 'BLACK' },
    Number = { fg = 'RED' },
    Operator = { fg = 'WHITE' },
    PreProc = { fg = 'MAGENTA' },
    Special = { fg = 'BLUE' },
    SpecialKey = { fg = 'darker_gray', bg = 'BLACK' },
    Statement = { fg = 'RED' },
    StorageClass = { fg = 'GREEN', italic = true },
    String = { fg = 'GREEN' },
    Tag = { fg = 'RED' },
    Title = { fg = 'WHITE', bold = true },
    Todo = { bg = 'MAGENTA', bold = true },
    Type = { fg = 'BLUE' },
    Underlined = { underline = true },

    ['@variable'] = { fg = 'WHITE' },

    htmlTag = { fg = 'RED', italic = true },
    htmlEndTag = { fg = 'RED', italic = true },
    htmlTagName = { fg = 'BLUE' },
    htmlArg = { fg = 'YELLOW' },
    htmlSpecialChar = { fg = 'MAGENTA' },

    ['@constructor.go'] = { fg = 'MAGENTA' },
    ['@constant.builtin.go'] = { fg = 'MAGENTA' },

    asmLabel = { fg = 'YELLOW' },

    fasmLabel = { fg = 'YELLOW' },
    nasmLabel = { fg = 'YELLOW' },
    nasmLocalLabel = { fg = 'YELLOW' },
    nasmInstructionStandard = { fg = 'MAGENTA' },

    ['@property.lua'] = { fg = 'YELLOW', bold = true },
    ['@constructor.lua'] = { fg = 'WHITE' },

    vimGroupName = { fg = 'GREEN' },
    vimGroup = { fg = 'GREEN' },
    vimOption = { fg = 'GREEN' },
    -- vimHiCtermFgBg = {},
    -- vimHiGuiFgBg = {}

    TabLineFill = { fg = 'darker_gray', bg = 'BLACK' },
    TabLine = { fg = 'GRAY', bg = 'BLACK' },
    TabLineSel = { fg = 'WHITE', bg = 'BLACK' },
}
